### ISSUE TITLE
This does not make sense

### ISSUE THREAD

**Issue by sen1** [Alximik5282/pwp-capstones#10]
https://github.com/Alximik5282/pwp-capstones/blob/d887388d61004e24387fffbc05f86cd7d8c9ab8f/final_projects/TomeRater.py#L128-L131

**Comment by Alximik5282** [comment]
And now?
for keys in self.books.keys():
                if book not in keys:
                    self.books[book] = 0
                elif book in keys:
                    self.books[book] += 1

**Comment by Alximik5282** [comment]
ok
