### ISSUE TITLE
Rubric score

### ISSUE THREAD

**Issue by sen1** [Alximik5282/pwp-capstones#11]
### Criteria 1: Valid Python Code
*  1 (Does Not Meet Expectations)
* You are getting there but there are still a lot of work to finish the project successfully.
 
### Criteria 2: Implementation of Project Requirements
* 1 (Does Not Meet Expectations)
* Code crashes and full of bugs.
 
### Criteria 3: Software Architecture
* 1 (Does Not Meet Expectations)
* Some mistakes makes the software bad to use.
 
### Criteria 4: Uses Python Language Features
* 1 (Does Not Meet Expectations)
* Needs more work.
 
### Overall Score: 4/16
Sorry for disappointing marks. There are more issues with your code than I mentioned in the issues. I would suggest to work more on the project and submit again.

**Comment by Alximik5282** [comment]
ok, thanks for the pretty quick answer
I will fix our mistakes and send our project again
