### ISSUE TITLE
Whats the use of this one?

### ISSUE THREAD

**Issue by sen1** [Alximik5282/pwp-capstones#3]
https://github.com/Alximik5282/pwp-capstones/blob/d887388d61004e24387fffbc05f86cd7d8c9ab8f/final_projects/TomeRater.py#L6

This is only used in `__repr__` function. Remember more the number of values to store, the bigger the object is in size. Generally, the best practice is not to add more unnecessary variables unless needed. Let's say you have millions of users and one less variable can really save some memory. If you need it you can make this variable inside `__repr__`.

**Comment by Alximik5282** [comment]
understood
