### ISSUE TITLE
wrong function

### ISSUE THREAD

**Issue by sen1** [Alximik5282/pwp-capstones#4]
https://github.com/Alximik5282/pwp-capstones/blob/d887388d61004e24387fffbc05f86cd7d8c9ab8f/final_projects/TomeRater.py#L18-L21 

That does not make any sense. Here is how I would do it:
```
def __eq__(self, other_user):
        if self.name == other_user.name and self.email == other_user.email:
            return True
        return False
```

**Comment by Alximik5282** [comment]
ok
