### ISSUE TITLE
wrong constructor

### ISSUE THREAD

**Issue by sen1** [Alximik5282/pwp-capstones#8]
https://github.com/Alximik5282/pwp-capstones/blob/d887388d61004e24387fffbc05f86cd7d8c9ab8f/final_projects/TomeRater.py#L75-L79

Revisit the inheritance in python lessons. 
```
def __init__(self, title, author, isbn):
        Book.__init__(self, title, isbn)
        self.author = author
```

**Comment by Alximik5282** [comment]
ok
